/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-09-22 13:37:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import menu.db.connection.DBConnection;
import org.apache.commons.io.output.ByteArrayOutputStream;
import java.io.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

public final class sugViewEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("menu.db.connection.DBConnection");
    _jspx_imports_classes.add("java.awt.image.BufferedImage");
    _jspx_imports_classes.add("org.apache.commons.io.output.ByteArrayOutputStream");
    _jspx_imports_classes.add("javax.imageio.ImageIO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>미급알 : 건의사항 작성하기</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script>\r\n");
      out.write("    \twindow.onload=function(){\r\n");
      out.write("    \t\tdocument.form.ctitle.focus();\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction check(){\r\n");
      out.write("\t\t\tdocument.forms['form'].submit();\t\r\n");
      out.write("\t\t}//function check()\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#box{\r\n");
      out.write("    background-color:#ffc400;\r\n");
      out.write("    border-radius:30px;\r\n");
      out.write("    padding:1%;\r\n");
      out.write("    width:90%;\r\n");
      out.write("}\r\n");
      out.write("#dbox{\r\n");
      out.write("    background-color:#311b1b;\r\n");
      out.write("    color:white;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    padding:3%;\r\n");
      out.write("    margin-bottom:1%;\r\n");
      out.write("}\r\n");
      out.write("#dbox a{\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("#dbox a:hover{\r\n");
      out.write("    color:#ed6853;\r\n");
      out.write("}\r\n");
      out.write("#mbox{\r\n");
      out.write("    background-color:#311b1b;\r\n");
      out.write("    color:#ed6853;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    padding:3%;\r\n");
      out.write("    margin-bottom:1%;\r\n");
      out.write("}\r\n");
      out.write("#mbox a{\r\n");
      out.write("    color:#ed6853;\r\n");
      out.write("}\r\n");
      out.write(".thumbnail{\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\theight:150px;\r\n");
      out.write("}\r\n");
      out.write(".link{\r\n");
      out.write("\tcolor:#311b1b;\r\n");
      out.write("}\r\n");
      out.write("b:hover{\r\n");
      out.write("\tcolor:#ed6853;\r\n");
      out.write("}\r\n");
      out.write("#specific{\r\n");
      out.write("\tborder: 2px solid #311b1b;\r\n");
      out.write("\tbackground-color:#ffc400;\r\n");
      out.write("\tborder-collapse:collapse;\r\n");
      out.write("}\r\n");
      out.write(".text{\r\n");
      out.write("\tborder-radius:10px;\r\n");
      out.write("\tborder:0;\r\n");
      out.write("\toutline:0;\r\n");
      out.write("\tpadding-left:5px;\r\n");
      out.write("\tfont-size:110%;\r\n");
      out.write("}\r\n");
      out.write(".btn{\r\n");
      out.write("\tbackground-color:#311b1b;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tborder:0;\r\n");
      out.write("\toutline:0;\r\n");
      out.write("\tpadding:3%;\r\n");
      out.write("\tfont-size:120%;\r\n");
      out.write("}\r\n");
      out.write("#bbox{\r\n");
      out.write("    background-color:#311b1b;\r\n");
      out.write("    color:#15a100;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    padding:3%;\r\n");
      out.write("    margin-bottom:1%;\r\n");
      out.write("}\r\n");
      out.write("#bbox a{\r\n");
      out.write("    color:#15a100;\r\n");
      out.write("}\r\n");
      out.write("#ybox{\r\n");
      out.write("    background-color:#311b1b;\r\n");
      out.write("    color:#fce803;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    padding:3%;\r\n");
      out.write("    margin-bottom:1%;\r\n");
      out.write("}\r\n");
      out.write("#ybox a{\r\n");
      out.write("    color:#fce803;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topp.jsp", out, false);
      out.write("<p>\r\n");

	request.setCharacterEncoding("utf-8");
	
	Cookie[] cookies=request.getCookies();
	String id="";
		
	for(int i=0; i<cookies.length; i++){
		if(cookies[i].getName().equals("id")){
	    	id=cookies[i].getValue();
		}
	}
	//db연결
	Connection conn=null;
	PreparedStatement pstmt=null;
	ResultSet rs=null;
	
	String sql="";

      out.write("\t\r\n");
      out.write("<form name=\"form\" action=\"sugViewEnrollProc.jsp\" method=\"post\">\r\n");
      out.write("<table id=\"whole\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td width=\"5%\"></td>\r\n");
      out.write("           <td width=\"20%\" style=\"vertical-align:top;\">\r\n");
      out.write("           \t<div id=\"box\" align=\"center\">\r\n");
      out.write("           \t\t<br><font style=\"font-size:150%;\">마이페이지<p></font>\r\n");
      out.write("           \t\t");
      out.print(id );
      out.write("님 환영합니다 :)<p>\r\n");
      out.write("           \t</div><p>\r\n");
      out.write("           \t");
if(id.equals("admin")){ 
      out.write("\r\n");
      out.write("           \t\t<div id=\"dbox\" align=\"center\"><a href=\"infoChange.jsp\">정보수정</a></div>\r\n");
      out.write("           \t\t<div id=\"dbox\" align=\"center\"><a href=\"memberCtrl.jsp\">회원관리</a></div>\t\r\n");
      out.write("           \t\t<div id=\"dbox\" align=\"center\"><a href=\"menuCtrl.jsp\">메뉴 관리</a></div>\r\n");
      out.write("           \t");
}else {
      out.write("\r\n");
      out.write("           \t\t<div id=\"dbox\" align=\"center\"><a href=\"infoChange.jsp\">정보수정</a></div>\r\n");
      out.write("           \t\t<div id=\"dbox\" align=\"center\"><a href=\"sugViewEnroll.jsp\">건의사항 등록하기</a></div>\r\n");
      out.write("           \t");
} 
      out.write("\r\n");
      out.write("           </td>\r\n");
      out.write("           <td width=\"5%\"></td>\r\n");
      out.write("           <td width=\"65%\">\r\n");
      out.write("           \t<div id=\"box\" align=\"center\">\r\n");
      out.write("           \t<table id=\"whole\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"box\" align=\"center\">\r\n");
      out.write("\t\t\t\t<h2>건의사항 작성</h2>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<table width=\"110%\">\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                \t<font size=\"4%\">제목</font>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                \t<input type=\"text\" size=50 name=\"title\" class=\"text\"><p>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                \t<font size=\"4%\">작성자</font>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                \t<input type=\"text\" name=\"id\" class=\"text\" size=30 value=\"");
      out.print(id );
      out.write("\"><p>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                \t<td>\r\n");
      out.write("\t\t                \t<font size=\"4%\">내용</font>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t                <td colspan=2>\r\n");
      out.write("\t\t                \t<input type=\"text\" name=\"content\" class=\"text\" size=80><p>\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                \t<td colspan=2 align=\"center\">\r\n");
      out.write("\t                \t\t<input type=\"button\" id=\"enroll\" class=\"btn\" value=\"등록하기\" onclick=\"check()\">\r\n");
      out.write("\t                \t</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("            \t</table>\r\n");
      out.write("            \t</table>\r\n");
      out.write("           \t</div>\r\n");
      out.write("           </td>\r\n");
      out.write("           <td width=\"5%\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("</table>  \r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
